name = "EpicHyperSketch"
uuid = "c73a71ba-f77a-4450-b81e-a1166e41307d"
authors = ["Shane Kuei-Hsien Chu (skchu@wustl.edu)"]
version = "0.0.4"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"

[compat]
julia = "1.10 - 1"
CUDA = "5.8.5 - 5.9"
Combinatorics = "1.0"
DataFrames = "1.8"
IterTools = "1.10"
ProgressMeter = "1.11"


[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
